# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["jchampion@fastly.com"]
description = ""
language = "other"
manifest_version = 3
name = "polyfill-service-rs"
# dev
service_id = "SwocX8EOEFupaPvw9Atx04"
# qa
# service_id = ""
# prod
# service_id = "Pg4HC9N6hckSWumOF1oEl1"

[scripts]
  build = "cargo build --bin service --release --target wasm32-wasi --color always -p service && cp target/wasm32-wasi/release/service.wasm bin/main.wasm"

[local_server]
  [local_server.kv_stores]
    [[local_server.kv_stores.polyfill-library]]
      key = "dummy"
      data = "This is some data"